Events: added support for np.nan
aeye-lab/pymovements pull request #198
Opened 2023-02-23 14:35 UTC by prassepaul

## Description

Please include a clear and concise description of the change and which issue is fixed.
Please also include excepted improvements, relevant motivation and context.
List any dependencies that are required for this change.

Fixes issue #

## Implemented changes

Insert a description of the changes implemented in the pull request.

- [ ] added np.nan support for the event detection algos (added np.nanmean, np.nanmax)
- [ ] created test-cases for np.nan in position and velocities

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change is or requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration

- [ ] added test-cases

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ x I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-02-24 11:58 UTC, dkrako requested changes
I think that it's unexpected that a consecutive sequence of `nan` is a positive for a detected event.

After all, maybe it makes more sense to treat `nan` as not belonging to the event?
I would prefer this behavior at least.

2023-02-24 13:47 UTC, prassepaul commented
I think I will implement the behavior as discussed in the meeting:
- do not consider nans during the calculation and delete nans in the beginning and at the end
- add a flag to filter events with nans inside (-> create individual events)

2023-02-27 17:01 UTC, dkrako requested changes
Thanks for all this work and also writing all these tests!

Regarding the functionality:
I think it would be best to rename `flag_split_at_nan` into `include_nan`.
See my comments for `engbert.py` in L43.

2023-02-27 21:46 UTC, dkrako commented on src/pymovements/events/engbert.py
> +            np.isnan(velocities[:, 0]),
or actually write it like this:
```
np.isnan(velocities).any(axis=1)
```
This doesn't enforce that nans have to be equal on both channels.

2023-02-28 08:33 UTC, prassepaul commented on src/pymovements/events/engbert.py
> +    flag_split_at_nan: bool = True,
ok. I think you are right. It was from a implementing persepective. I will rename the parameter.

2023-02-28 09:42 UTC, prassepaul commented on src/pymovements/events/engbert.py
> +    outside_ellipse_indices = np.where(
you are right. I changed it in the code

2023-02-28 09:43 UTC, prassepaul commented on src/pymovements/events/engbert.py
> +            np.isnan(velocities[:, 0]),
added check for both channels

2023-02-28 09:47 UTC, prassepaul commented on src/pymovements/events/engbert.py
> +    # check if np.nan is in data
I think this is no problem any more.

2023-02-28 09:47 UTC, prassepaul commented on src/pymovements/events/engbert.py
> +    if flag_contains_nans:
done.

2023-02-28 09:51 UTC, prassepaul commented on src/pymovements/events/ivt.py
> +        flag_split_at_nan: bool = True,
done

2023-02-28 09:53 UTC, prassepaul commented on src/pymovements/events/idt.py
> +        flag_split_at_nan: bool = True,
done

2023-02-28 15:56 UTC, dkrako requested changes
Final minor changes requested, won't take much.
Thanks a lot for the work!

2023-03-01 11:47 UTC, dkrako approved these changes
LGTM!

2023-03-01 11:49 UTC, merged