Add Heatmap plotting function and notebook for demonstration (#31)
aeye-lab/pymovements pull request #276
Opened 2023-03-13 20:29 UTC by jakobchwastek

## Description

I implemented a heatmap function using `histogram2d` and `imshow` and a very very basic notebook. I used imshow cause i thought  it has better interpolation capabilities than `pcolormesh`. Maybe you have to correct me. 
Please have a look and tell me what needs to be adjusted.

Fixes issue #31

## Implemented changes

Insert a description of the changes implemented in the pull request.

- [x] Implement heatmap function
- [ ] tutorial Notebook

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

This has just been tested by using the function in the tutorial notebook

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-03-14 10:34 UTC, dkrako requested changes
This is very clean and has a clever way of using the experiment definition from the gaze dataframe.

I would just like to remove the `origin` argument from the plotting function.
this should be inferable from the `experiment.screen.origin` shouldn't it?

Is this related to the bug which you mentioned, where the origin should actually be `upper left` instead `lower left`?

2023-03-14 10:36 UTC, dkrako requested changes

2023-03-14 10:36 UTC, dkrako commented on src/pymovements/plotting/heatmap.py
> +import matplotlib.pyplot as plt
you need an additional import to get rid of all the test errors:

```
from __future__ import annotations
```

2023-03-14 16:49 UTC, jakobchwastek commented
> I would just like to remove the `origin` argument from the plotting function.
> this should be inferable from the `experiment.screen.origin` shouldn't it?
> 
> Is this related to the bug which you mentioned, where the origin should actually be `upper left` instead `lower left`?

Yes, but i think when data is loaded with the correct origin in the first place it is not necessary to use origin here at all. How I understand all data should have the same coordinates system when choosing the correct origin in the Experiment/Screen class.

So should I remove argument or leave it for now?

2023-03-14 17:10 UTC, dkrako commented
> Looks like there is a problem because GazeDataFrame.experiment is optional..

Hmm.. okay then for this PR let's just raise an exception if experiment is None

2023-03-14 17:11 UTC, dkrako commented
If mypy still doesn't get it, just add a line with `assert gaze.experiment is not None`

we will fix this in a future PR

2023-03-15 13:02 UTC, dkrako requested changes

2023-03-15 13:04 UTC, dkrako requested changes

2023-03-15 13:04 UTC, dkrako commented on src/pymovements/plotting/heatmap.py
> +    heatmap, x_edges, y_edges = np.histogram2d(x, y, bins=[x_bins, y_bins])
naming the variable `heatmap` is problematic as it is also the function name.
our linters don't accept that.

name the variable `heatmap_values` or similar

2023-03-15 13:05 UTC, dkrako requested changes
for testing you can just copy the testing functions from here:
https://github.com/aeye-lab/pymovements/blob/main/tests/plotting/traceplot_test.py

then just adjust the function and parameter names accordingly to get 100% coverage.

2023-03-16 09:14 UTC, dkrako approved these changes
Thanks a lot! LGTM!

2023-03-16 09:15 UTC, merged