Feature: added styling args to main seq plot
aeye-lab/pymovements pull request #458
Opened 2023-07-07 09:36 UTC by theDebbister

## Description

Fixes issue #449 

## Implemented changes

- [x] Added styling args to main sequence plot: color, marker_size, ...
- [x] possible to add further kwargs for plot.scatter

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change is or requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-07-12 10:54 UTC, SiQube commented
the type for **kwargs comes from [plt scatter documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html)

2023-07-28 08:38 UTC, dkrako reviewed
Can you also update the tutorial a bit with some of the new parameters?

That would be my only change request.
Apart from that, this looks fine!

2023-07-28 08:38 UTC, dkrako commented on src/pymovements/plotting/main_sequence_plot.py
> +        **kwargs: Collection,
I'm not sure if I understand the typehint here, but if mypy is happy, I am also happy

2023-07-28 08:40 UTC, dkrako requested changes
.

2023-07-28 14:36 UTC, dkrako approved these changes
LGTM!

2023-07-28 14:39 UTC, merged