chore!: Drop support for python 3.7
aeye-lab/pymovements pull request #460
Opened 2023-07-07 12:02 UTC by SiQube

resolves #457

2023-07-07 14:04 UTC, SiQube commented
I additionally removed mandatory checks for 3.7

2023-07-28 08:31 UTC, dkrako requested changes
I confirm that the walrus operator decreases readability in most cases.

I basically follow this line of thought:
https://therenegadecoder.com/code/the-controversy-behind-the-walrus-operator-in-python/

I think there are cases though, where the walrus operator indeed makes sense.
In this PR I would say that the regex match if clauses are perfectly fine with the walrus operator.

Please add `consider-using-assignment-expr` to the `pylintrc` under `disable`, maybe sort the entries alphabetically if you're at it.

Apart from that, thanks for all the work!

2023-07-28 08:31 UTC, dkrako commented on src/pymovements/utils/parsing.py
> +            if match := pattern_dict['pattern'].match(line):
I think the walrus operator is handy for matching regexes (I always hated it to write two lines for this).

So keep this please.

2023-07-28 08:31 UTC, dkrako commented on src/pymovements/utils/paths.py
> +        elif (match := regex.match(childpath.name)) is not None:
Keep this please, but leave the `is not None` out

2023-07-28 10:25 UTC, dkrako requested changes
I remembered one more thing which was necessary due to py37 support.

python 3.8 now has `typing.Literal` so we don't need `typing_extensions` anymore.

https://github.com/aeye-lab/pymovements/blob/e3ef6c91fd8671f6cba305cd645d7371c319f711/src/pymovements/gaze/integration.py#L26

Please also remove this dependency from the `pyproject.toml`:

https://github.com/aeye-lab/pymovements/blob/e3ef6c91fd8671f6cba305cd645d7371c319f711/pyproject.toml#L41

2023-07-28 10:32 UTC, dkrako commented
One more thing which I am unsure of: do we still need `from __future__ import annotations` everywhere?

We have this special pre-commit hook to add it everywhere:

https://github.com/aeye-lab/pymovements/blob/e3ef6c91fd8671f6cba305cd645d7371c319f711/.pre-commit-config.yaml#L21-L27

I'm not sure if this was due to python3.7 issues or if thisissue  will remain with python3.8?

2023-08-09 11:18 UTC, SiQube commented
> One more thing which I am unsure of: do we still need `from __future__ import annotations` everywhere?
> 
> We have this special pre-commit hook to add it everywhere:
> 
> https://github.com/aeye-lab/pymovements/blob/e3ef6c91fd8671f6cba305cd645d7371c319f711/.pre-commit-config.yaml#L21-L27
> 
> I'm not sure if this was due to python3.7 issues or if thisissue will remain with python3.8?

This will remain since there are changes from 3.8 => 3.9 and so on, e.g. [here are some 3.12 typing changes](https://docs.python.org/3.12/whatsnew/3.12.html). so I'd keep it!

2023-08-09 13:53 UTC, dkrako approved these changes

2023-08-09 13:53 UTC, dkrako commented
Thanks a lot for all the work!

2023-08-09 13:54 UTC, merged