Dataset gazeonfaces
aeye-lab/pymovements pull request #567
Opened 2023-09-21 12:38 UTC by prassepaul

## Description

added GazeOnFaces dataset

Fixes issue #

## Implemented changes

Insert a description of the changes implemented in the pull request.

- [x] Added a new dataset: GazeOnFaces

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-09-21 14:49 UTC, SiQube approved these changes

2023-09-22 07:05 UTC, dkrako requested changes
Thanks a lot! 

please also add the two relevant test cases to https://github.com/aeye-lab/pymovements/blob/main/tests/datasets/datasets_test.py

2023-09-22 07:05 UTC, dkrako commented on src/pymovements/datasets/__init__.py
> +    'GazeOnFaces',
please sort in alphabetically

2023-09-22 07:30 UTC, prassepaul commented on src/pymovements/datasets/__init__.py
> +    'GazeOnFaces',
k

2023-09-22 07:33 UTC, dkrako approved these changes
Great! Thanks a lot!

2023-09-22 07:51 UTC, merged