401 Remove top-level directory from extracted files if it has only single child
aeye-lab/pymovements pull request #579
Opened 2023-09-26 07:48 UTC by josephine-funken

## Description

Removes top-level directories from extracted files if its only child is a directory.
This top-level directory in the archive is unnecessary and creates longer file paths than needed.

Fixes issue #401 

## Implemented changes

- [ ] Remove top-level directories by default in `Dataset.extract()`, `dataset_download.extract_dataset()` and `utils.archives.extract_archive()`.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- [ ] `tests/utils/archives_test.test_extract_archive_destination_path_None()`
- [ ] `test_extract_archive_destination_path_not_None()`

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-09-26 16:12 UTC, SiQube commented
@josephine-funken thank you for this great work! there seems to be a merge conflict which needs to be removed first -- if you have any questions how to resolve it feel free to reach out.

2023-09-27 09:11 UTC, josephine-funken commented
Added functionality to remove top-level directories to `downloads.download_and_extract_archive()` and added parameter to corresponding test.

2023-09-28 13:15 UTC, dkrako requested changes
Thank you very much for this work!

However I would like to request two changes.

- [x] change the file-handling from copy/remove to move/remove
- [x] the `elif` clause can probably be refactored into the if clause which would hopefully raise coverage to 100%

2023-09-28 13:15 UTC, dkrako commented on src/pymovements/utils/archives.py
> +        elif len(children) == 2 and destination_path == source_path.parent:
this branch doesn't seem to be covered by tests.
maybe it makes sense to combine the `elif` condition into the `if` a few lines before?

2023-10-12 12:12 UTC, josephine-funken commented on src/pymovements/utils/archives.py
> +                shutil.copytree(single_child, destination_path, dirs_exist_ok=True)
I applied this change

2023-10-13 08:46 UTC, dkrako approved these changes
Great clean work! Thanks a lot!

2023-10-13 08:56 UTC, merged