PoTeC Dataset
aeye-lab/pymovements pull request #636
Opened 2023-12-04 11:17 UTC by prassepaul

## Description

This PR adds the PoTeC dataset to pymovements.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-12-04 12:33 UTC, SiQube commented on docs/source/bibliography.bib
> +}
okay then we should add an issue after this PR is merged

2023-12-06 13:30 UTC, dkrako approved these changes
Somehow the dataset ist not part of `DatasetLibrary` and I don't get why.

- [ ] Please add the respective test cases to this file:
https://github.com/aeye-lab/pymovements/blob/main/tests/unit/datasets/datasets_test.py

- [ ] make sure that the integration test passes

You can run a single test case like this:
```bash
pytest tests/integration/public_dataset_processing_test.py::test_public_dataset_processing[PoTeC]
```

2023-12-06 13:30 UTC, dkrako commented on src/pymovements/datasets/potec.py
> +    The Potsdam Textbook Corpus (PoTeC) is a corpus of eye-tracking-while-reading data where
can you add which eye is recorded to the docstring?

2023-12-06 13:30 UTC, dkrako commented on src/pymovements/datasets/potec.py
> +"""This module provides an interface to the JuDo1000 dataset."""
copy pasta

2023-12-06 13:31 UTC, dkrako requested changes
haha not so fast, I clicked the wrong box, Reguest changes it is!

2023-12-07 12:20 UTC, prassepaul commented on src/pymovements/datasets/potec.py
> +"""This module provides an interface to the JuDo1000 dataset."""
done

2023-12-07 12:21 UTC, prassepaul commented
> Somehow the dataset ist not part of `DatasetLibrary` and I don't get why.
> 
> * [x]  Please add the respective test cases to this file:
>   https://github.com/aeye-lab/pymovements/blob/main/tests/unit/datasets/datasets_test.py
> * [x]  make sure that the integration test passes
> 
> You can run a single test case like this:
> 
> ```shell
> pytest tests/integration/public_dataset_processing_test.py::test_public_dataset_processing[PoTeC]
> ```

To perform the pytest, you need to install pymovements from path....

2023-12-07 19:02 UTC, merged