remove type from tests/events/test_events_base.py to conform with rest of test suite
aeye-lab/pymovements pull request #69
Opened 2022-11-09 16:59 UTC by SiQube

## Description
I removed type hints from one test file to match the rest of the tests -- generally I think we do not need to type tests because we're checking type hints with type checkers and tests are for functionality. functionallity should fail given the wrong type.

## Implemented changes
- Insert a description of the changes implemented in the pull request.
  - [ ] removed typing hint from tests/events/test_events_base.py 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-11-09 18:09 UTC, dkrako commented
yes you're totally right, this is a good idea.

2022-11-09 18:10 UTC, dkrako requested changes
Thank you very much for your effort!

2022-11-09 18:10 UTC, dkrako commented on tests/events/test_events_base.py
>  from __future__ import annotations
we can also remove this import then

2022-11-10 08:53 UTC, SiQube commented on tests/events/test_events_base.py
>  from __future__ import annotations
did it in newest commit

2022-11-11 12:22 UTC, dkrako reviewed
LGTM

2022-11-11 12:23 UTC, merged