enable fixation only datasets
aeye-lab/pymovements pull request #771
Opened 2024-08-05 13:54 UTC by SiQube

eventually resolves #716

2024-08-17 19:25 UTC, SiQube commented
for pre-commit ci to pass need to merge #774 first

2024-08-20 17:00 UTC, SiQube commented
resolves #716

2024-08-22 14:45 UTC, SiQube commented
we have to think about [integration tests](https://github.com/aeye-lab/pymovements/blob/main/tests/integration/public_dataset_processing_test.py) when considering this feature.

we may have to add a line which checks whether `has_gaze_files` is true. if not true, skip test. 


secondly, we may have to add integration tests, for datasets which just have `has_precomputed_event_files`. this might be more difficult as we do not enforce any standardized notations.

2024-08-26 13:44 UTC, prassepaul commented on src/pymovements/events/precomputed.py
> +"""Module for the TextDataFrame."""
TextDataFrame sounds weird. Would change it to 'Module for the precomputed events'

2024-08-26 13:45 UTC, prassepaul requested changes
I would only change the small thing pointed out... really big PR...

2024-08-26 14:16 UTC, prassepaul approved these changes

2024-08-26 14:22 UTC, merged