Scanpathplot
aeye-lab/pymovements pull request #782
Opened 2024-08-20 19:51 UTC by SiQube

## Description

add feature to plot scanpaths

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2024-08-20 19:52 UTC, SiQube commented
still #774 for pre-commit ci

2024-09-02 08:55 UTC, prassepaul commented on src/pymovements/plotting/scanpathplot.py
> +        Relative padding factor to construct padding value if not given. (default: None)
default is 0.05

2024-09-02 08:59 UTC, prassepaul requested changes
Please change the defaults to the correct values.

2024-09-02 09:57 UTC, prassepaul approved these changes

2024-09-02 09:57 UTC, merged