feat: aoi mapping extended to end coordinate instead of width/height
aeye-lab/pymovements pull request #851
Opened 2024-10-17 16:31 UTC by SiQube

previously we were only able to map fixations to aoi via `width` and `height`. this PR introduces also `end_coordinate_column` to map fixaitons to aois.

2024-10-17 19:23 UTC, prassepaul commented on src/pymovements/stimulus/text.py
> +    end_y_column: str | None
default is missing

2024-10-17 19:26 UTC, prassepaul requested changes
see comment

2024-10-17 22:32 UTC, SiQube commented
good catch -- thank you -- changed!

2024-10-18 11:42 UTC, prassepaul approved these changes

2024-10-19 08:42 UTC, merged